customhost = "database-1.cxpaxbrdjbjl.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "ianlaiwenkye-employee"
customregion = "us-east-1"
